[github]
username = "dicastro"
configuration_backup_filename = "site_configuration_backup.json"

[pvgis]
calibrate_angle_and_aspect = true

[pvgis.params]
loss = 14
peakpower = [ 1.8, 2.25, 2.7, 3.15, 3.6 ]
angle = 39
aspect = -6
