[github]
username = "dicastro"
configuration_backup_filename = "site_configuration_backup.json"

[pvgis]
calibrate_angle_and_aspect = false

[pvgis.params]
loss = 14
peakpower = 2
angle = 39
aspect = -6
