[github]
username = "dicastro"
configuration_backup_filename = "site_configuration_backup.json"

[pvgis]
calibrate_angle_and_aspect = false

[pvgis.params]
loss = 14
peakpower = [ 2.46, 3.28, 4.1, 4.92,]
angle = [ 0, 10, 20, 36, 39,]
aspect = [ -6, 0,]
